### PR TITLE
debug install-tl.sh script

### PR DESCRIPTION
**Pull request by tamsky**

### CODE REVIEW

**Comment by tamsky** [comment]
Was hoping my PR would be built by travis, but sadly it is not.

`Build type disabled via repository settings (pull_request).`

Closing due to inability to debug failing travis build.

**Comment by seisman** [comment]
Build for pull request is opened now. Feel free to reopen this PR.

**Comment by tamsky** [comment]
https://tex.stackexchange.com/questions/415604/tex-live-download-fails

is similar to the current travis failure:

```
++ ./install-tl --version
++ egrep -o 20..
+ TEXLIVE=2017
+ TEXBIN=/usr/local/texlive/2017/bin/x86_64-linux
+ ./install-tl -q -profile texlive.profile -repository http://ctan.sharelatex.com/tex-archive/systems/texlive/tlnet
TLUtils::check_file: removing /tmp/RJ4KyIykg2/9h1YRkz5h7/awesomebox.tar.xz, checksums differ:
TLUtils::check_file:   TL=74a9205fa82fd375d521a04f4518566536ba04dac33bdc77b8c3762cb0dd1be9f8680827cdc3df510319e592670d39474d1049f09e81810e5f5592461034ed12, arg=3a23dfc7f5354036b62725015bab3b921a1c617dc0be4e69f23c49ce9b31fc6d73daf396b3a66794d5a7aa24dbc4b41056bf04cd5700b831fc3a72523bd45356
TLPDB::_install_package: downloading did not succeed
Installation failed.
Rerunning the installer will try to restart the installation.
Or you can restart by running the installer with:
  install-tl --profile installation.profile [EXTRA-ARGS]
./install-tl: Writing log in current directory: /tmp/install-texlive/install-tl.log
```

**Comment by seisman** [comment]
The new script has some syntax errors. It may be better to write the "TeXLive installation" to a bash script, and run the script in travis.yml.

**Comment by tamsky** [comment]
Thanks.

I'm still working through these errors, though I may do as you suggest.

My YAML skills are typically more polished than this.

**Comment by seisman** [comment]
The travis failure is due to the breakdown of ctan mirror (http://ctan.sharelatex.com/tex-archive/systems/texlive/) I used in the TeXLive installation script. I have changed the mirror to fix the issue. Now everything works.

**Comment by tamsky** [comment]
Have you considered using the mirror multiplexor instead of hardcoding one?
http://mir­ror.ctan.org/

**Comment by seisman** [comment]
Good point. The [TeXLive install script]( https://gist.github.com/seisman/ad00252a9f03fc644146a11e6983d9c5) now uses http://mir­ror.ctan.org/.

**Pull request closed without merging**
